wechat:
  mp:
    appId: wxf985df3154d6f74b
    secret: 49c13833c5740e2dc4743a04d693411f
    echo-token: 123
  pay:
    mchId: 1582615011
interceptor:
  patterns:
    include: /**
    exclude: /**
#阿里云
#短信服务
aliyun:
  sms:
    access-key: LTAI4FmUG7wjzxuqD8KvWYc9
    access-key-secret: FMiLTyiX2NAWT57kU1ngtfx66PKsLl
    domain-name:
    region:
    version: