package com.xiaozipu.dao.mapper;

import com.xiaozipu.dao.entity.TSpecName;
import com.xiaozipu.dao.entity.TSpecNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSpecNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    long countByExample(TSpecNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int deleteByExample(TSpecNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int insert(TSpecName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int insertSelective(TSpecName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    List<TSpecName> selectByExample(TSpecNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    TSpecName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSpecName record, @Param("example") TSpecNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSpecName record, @Param("example") TSpecNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSpecName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSpecName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TSpecName> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_name
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TSpecName> list, @Param("selective") TSpecName.Column ... selective);
}