package com.xiaozipu.dao.mapper.generator;

import com.xiaozipu.dao.entity.generator.TProductImage;
import com.xiaozipu.dao.entity.generator.TProductImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProductImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    long countByExample(TProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int deleteByExample(TProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int insert(TProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int insertSelective(TProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    List<TProductImage> selectByExample(TProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    TProductImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TProductImage record, @Param("example") TProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TProductImage record, @Param("example") TProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TProductImage> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_image
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TProductImage> list, @Param("selective") TProductImage.Column ... selective);
}