package com.xiaozipu.dao.mapper.generator;

import com.xiaozipu.dao.entity.generator.TProductSpecs;
import com.xiaozipu.dao.entity.generator.TProductSpecsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProductSpecsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    long countByExample(TProductSpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int deleteByExample(TProductSpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int insert(TProductSpecs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int insertSelective(TProductSpecs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    List<TProductSpecs> selectByExample(TProductSpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    TProductSpecs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TProductSpecs record, @Param("example") TProductSpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TProductSpecs record, @Param("example") TProductSpecsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TProductSpecs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TProductSpecs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TProductSpecs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_specs
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TProductSpecs> list, @Param("selective") TProductSpecs.Column ... selective);
}