package com.xiaozipu.dao.mapper.generator;

import com.xiaozipu.dao.entity.generator.TSpecValue;
import com.xiaozipu.dao.entity.generator.TSpecValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSpecValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    long countByExample(TSpecValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int deleteByExample(TSpecValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int insert(TSpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int insertSelective(TSpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    List<TSpecValue> selectByExample(TSpecValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    TSpecValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSpecValue record, @Param("example") TSpecValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSpecValue record, @Param("example") TSpecValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSpecValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TSpecValue> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_value
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TSpecValue> list, @Param("selective") TSpecValue.Column ... selective);
}