package com.xiaozipu.dao.mapper.generator;

import com.xiaozipu.dao.entity.generator.TUserThird;
import com.xiaozipu.dao.entity.generator.TUserThirdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserThirdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    long countByExample(TUserThirdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int deleteByExample(TUserThirdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int insert(TUserThird record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int insertSelective(TUserThird record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    List<TUserThird> selectByExample(TUserThirdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    TUserThird selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TUserThird record, @Param("example") TUserThirdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TUserThird record, @Param("example") TUserThirdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TUserThird record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TUserThird record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<TUserThird> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_third
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<TUserThird> list, @Param("selective") TUserThird.Column ... selective);
}