spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaozipu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: xzpHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    password:
    database: 0
  profiles:
    include: config/config-dev

mybatis:
  mapper-locations: classpath:mappers/*/*Mapper.xml #*可以表示任意目录